### ISSUE TITLE
Posix_spawn is not yet supported on powerpc-linux (powerpc64le-linux) for sensu package

### ISSUE THREAD

**Issue by sandipmgiri** [enkessler/childprocess#106]
I'm trying to build the sensu package on ubuntu_ppc64le:16.04. however getting the error, posix_spawn is not yet supported on powerpc-linux (powerpc64le-linux) for the command, bundle exec rake. PFA for the build steps .
[sensu.txt](https://github.com/enkessler/childprocess/files/383898/sensu.txt)

root@5fecaa965cf7:/sensu/sensu# bundle exec rake
/usr/share/rvm/rubies/ruby-2.3.0/bin/ruby -I/usr/share/rvm/gems/ruby-2.3.0/gems/rspec-core-3.0.4/lib:/usr/share/rvm/gems/ruby-2.3.0/gems/rspec-support-3.0.4/lib -S /usr/share/rvm/gems/ruby-2.3.0/gems/rspec-core-3.0.4/exe/rspec ./spec/api/client_validator_spec.rb ./spec/api/process_spec.rb ./spec/cli_spec.rb ./spec/client/process_spec.rb ./spec/client/socket_spec.rb ./spec/daemon_spec.rb ./spec/server/filter_spec.rb ./spec/server/handle_spec.rb ./spec/server/mutate_spec.rb ./spec/server/process_spec.rb ./spec/server/socket_spec.rb ./spec/utilities_spec.rb
..FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.........posix_spawn is not yet supported on powerpc-linux (powerpc64le-linux), falling back to default implementation. If you believe this is an error, please file a bug at http://github.com/jarib/childprocess/issues
....................................../usr/share/rvm/rubies/ruby-2.3.0/bin/ruby -I/usr/share/rvm/gems/ruby-2.3.0/gems/rspec-core-3.0.4/lib:/usr/share/rvm/gems/ruby-2.3.0/gems/rspec-support-3.0.4/lib -S /usr/share/rvm/gems/ruby-2.3.0/gems/rspec-core-3.0.4/exe/rspec ./spec/api/client_validator_spec.rb ./spec/api/process_spec.rb ./spec/cli_spec.rb ./spec/client/process_spec.rb ./spec/client/socket_spec.rb ./spec/daemon_spec.rb ./spec/server/filter_spec.rb ./spec/server/handle_spec.rb ./spec/server/mutate_spec.rb ./spec/server/process_spec.rb ./spec/server/socket_spec.rb ./spec/utilities_spec.rb failed
root@5fecaa965cf7:/sensu/sensu#

**Comment by jarib** [comment]
In order to support `posix_spawn` on `powerpc-linux`, ChildProcess needs to know the size of the `posix_spawn` structs on that platform.

If you clone this repo and run `rake generate`, it should generate a file for your platform that can be submitted as a pull request.

**Comment by sandipmgiri** [comment]
Thanks for the reply!!!

Getting rake aborted after running the command rake generate. Actually rake is new for me, so don't have a too much knowledge about rake.


root@d812fafaef76:/sensu/sensu# rake generate
rake aborted!
Don't know how to build task 'generate' (see --tasks)
/usr/share/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/usr/share/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
root@d812fafaef76:/sensu/sensu#


please reply!!!

**Comment by sandipmgiri** [comment]
With latest release of Sensu, i m not getting this error, hence closing this ticket.
