### ISSUE TITLE
Error 6: The handle is invalid

### ISSUE THREAD

**Issue by JoshCheek** [enkessler/childprocess#108]
Trying to launch a process, kill it if it times out, kill it if the process that launched it is interrupted. When it dies, it should take its descendants with it. It's working for me on my mac and on Travis (CI for Linux), but not on AppVeyor (CI for Windows). While tweaking different things, I've also seen error 5, "Access is denied" and I've had it just kill the tests without a backtrace when I tried stopping the child process and rescuing any `ChildProcess::Error`s from invalid handles.

* I've **[recreated](https://github.com/JoshCheek/childprocess_experiment/tree/697a4444c18950036e96d8ed90c3bd379bc5f3c6)** the issue so that it can be analyzed without the distraction of my gem.
* It **[fails](https://ci.appveyor.com/project/JoshCheek/childprocess-experiment/build/5)** on AppVeyor (Windows)
* It **[passes](https://travis-ci.org/JoshCheek/childprocess_experiment/builds/187606438)** on Travis (Linux)

**Comment by JoshCheek** [comment]
It seems the error occurs when you call `stop` after having called `wait`. When I added this test to your suite (screenshot b/c I don't know how to copy/paste through the VM barrier):

![screenshot 2016-12-31 01 53 58](https://cloud.githubusercontent.com/assets/77495/21576634/c71a9c1e-cefc-11e6-931e-7feb9f14cba9.png)

It blew up on the line where I called `stop` in the same way that my tests are:

![screenshot 2016-12-31 01 55 40](https://cloud.githubusercontent.com/assets/77495/21576635/c71b8c00-cefc-11e6-824d-1095f6237435.png)

I'm calling `stop` because it was leaving orphan processes before. But I'll see if there's not a way to get all my tests passing in both environments.

**Comment by JoshCheek** [comment]
Okay, got all the tests passing on [windows](https://ci.appveyor.com/project/JoshCheek/childprocess-experiment/build/13) and [unix](https://travis-ci.org/JoshCheek/childprocess_experiment/builds/187871803). Note that I do have to explicitly check what system I'm on

* In the [test](https://github.com/JoshCheek/childprocess_experiment/blob/226155/spec.rb#L7) to see how to detect whether the process is running.
* In the [implementation](https://github.com/JoshCheek/childprocess_experiment/blob/226155/run.rb#L35) to see whether I need to call `stop` or not (if I don't call it, Unix leaves orphans, if I do call it, Windows blows up, but I do need to call it on Windows when there is an error like an interrupt)

**Comment by enkessler** [comment]
@JoshCheek Okay. As you have already figured out, the problem does seem to stem from your code calling `Process#stop` after calling `Process#wait`. Essentially, you are telling the OS to kill a process that doesn't exist anymore and Windows particularly seems to not like that.

Rather than have the extra OS checks and lower level implementation, have you tried using `Process#exited?` in order to see if you still need to call stop? That should be more consistent across operating systems.

**Comment by enkessler** [comment]
@JoshCheek Did you get a chance to check out `Process.exited?`?

**Comment by JoshCheek** [comment]
I did try it but I didn't go with it. I don't remember why. Should have come back and updated the issue at that time.

I feel like it didn't work the way I needed it to (I have a vague memory that if I asked before calling `#wait`, that it would cause `#wait` to error instead and that I sometimes needed to be able to call it before calling `#wait`). But that could be a false memory. I seem to also remember reordering the code to where I didn't have the need for it, but I can't say if that's the reason I didn't use it, or if I did that because it wasn't working as expected. I also switched to [posix spawn](https://github.com/enkessler/childprocess/blob/ddde6c9dbf7146d9693410c0138807b4f951f816/lib/childprocess.rb#L84), which I think was a separate thing after the fact, but could have been related. Not super helpful, I know >.<

**Comment by enkessler** [comment]
So...reasons. Got it. ;)

At this point, is there still an issue that you need fixed? If not, feel free to close this Issue. If so, feel free to post another update that will help get you and I on the same page so that we can tackle stuff.

**Comment by JoshCheek** [comment]
I don't currently have an issue. Hopefully I've left enough breadcrumbs that anyone who hits this later can find and follow.
