### ISSUE TITLE
io.PIPE for stdout/stderr?

### ISSUE THREAD

**Issue by xanview** [enkessler/childprocess#11]
Being able to tell childprocess to use IO.pipe instead of Tempfile would be a great addition, so I can just do process.io.stdout.read() without having to output to a Tempfile or provide some kind of other IO.

Right now I do stdout_r, stdout_w = IO.pipe but that requires keeping the outside stdout_r object which kind of spoils the beauty of the self contained process object :)

**Comment by antoinelyset** [comment]
I do it too, and this is not really elegant. :)

**Comment by sds** [comment]
This is now possible: https://github.com/enkessler/childprocess#pipe-output-to-another-childprocess
