### ISSUE TITLE
Add Travis CI for Mac OS X versions to test matrix

### ISSUE THREAD

**Issue by ms-ati** [enkessler/childprocess#110]

**Comment by enkessler** [comment]
This should be available soon, although it will likely be a mere safety check as opposed to a practical development solution. Linux and Windows feedback is available within minutes but OSX feedback takes hours.

**Comment by enkessler** [comment]
@ms-ati Done.

https://travis-ci.org/enkessler/childprocess/builds/199826635

**Comment by ms-ati** [comment]
Awesome! 👍
