### ISSUE TITLE
Should be a public method: `#started?`

### ISSUE THREAD

**Issue by ms-ati** [enkessler/childprocess#120]
Shouldn't querying this state be a public API call?

**Comment by enkessler** [comment]
No, in the sense that it is not possible for the process to not be started after calling `#start`. Yes, in the sense that maybe it would be handy for oneself to not have to remember if they have called `#start` yet.

At first glance, I don't see a downside to making that method public.

**Comment by ms-ati** [comment]
If I have a method that accepts a `ChildProcess`, the intent is to be able to verify whether it is already `#started`. In that sense, it is an externally visible bit of state. Does that make sense?

**Comment by enkessler** [comment]
If you are getting the process object from someone else, then remembering that it has been started might not even be an option because you weren't the one that made it to begin with. So, sure, let's have a public `#started?` method.
