### ISSUE TITLE
Running another script inside the parent one not working

### ISSUE THREAD

**Issue by sebastianvirlan** [enkessler/childprocess#125]
Running another script inside the parent one not working.

For example:

ChildProcess.build("script.sh")

script.sh

```
#!/bin/bash
echo 'BAR'
data=$(ruby script.rb)
echo "$data"
```

script.rb

`puts 'FOO'`

The output is:

BAR

and the ruby file never executed. Same for python.

**Comment by sds** [comment]
FWIW, I can't reproduce:

**foo.sh**
```bash
#!/bin/bash
echo FOO
data=$(ruby bar.rb)
echo "$data"
```

**bar.rb**
```ruby
puts 'BAR'
```

Running the following:
```ruby
require 'childprocess'

p = ChildProcess.build('./foo.sh')
p.io.inherit!
p.cwd = Dir.pwd
p.start
p.wait
```
...returns the expected output:
```
FOO
BAR
```

It's possible you forgot the leading `./` in your `ChildProcess.build` arguments. Hope this helps!
