### ISSUE TITLE
cannot load such file -- ffi on windows

### ISSUE THREAD

**Issue by ahorek** [enkessler/childprocess#150]
after this change https://github.com/enkessler/childprocess/pull/132

ffi gem isn't part of the gemspec anymore and bundler doesn't require such dependencies

`require 'ffi'` will raise an error `LoadError: cannot load such file -- ffi` even if the gem is actually installed

<details>
<summary>backtrace</summary>
<pre>
LoadError: cannot load such file -- ffi
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/childprocess-1.0.1/lib/childprocess/windows.rb:1:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/childprocess-1.0.1/lib/childprocess/windows.rb:1:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/childprocess-1.0.1/lib/childprocess.rb:209:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/childprocess-1.0.1/lib/childprocess.rb:209:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.1/lib/selenium/webdriver.rb:20:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.1/lib/selenium/webdriver.rb:20:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.1/lib/selenium-webdriver.rb:20:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.1/lib/selenium-webdriver.rb:20:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
c:/redmine/config/application.rb:7:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
c:/redmine/Rakefile:5:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load_rakefile'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:703:in `raw_load_rakefile'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:104:in `block in load_rakefile'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:103:in `load_rakefile'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:82:in `block in run'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
C:/Ruby25-x64/bin/rake:23:in `load'
C:/Ruby25-x64/bin/rake:23:in `<main>'
</pre>
</details>

if I add `gem 'ffi'` into app's Gemfile it works fine, but I think that childprocess should require it as a dependency, not just install the gem under the hood.

**Comment by sds** [comment]
Hey @ahorek, what does `Gem.win_platform?` return for you?

The gem should install the `ffi` gem on Windows automatically. See: https://github.com/enkessler/childprocess/blob/982b1aea221ea5a1265c9e429a23887e7b3d10c3/ext/mkrf_conf.rb#L14-L16

**Comment by sds** [comment]
Sorry, I misread your comment.

This is likely because you are running your application via Bundler. With Bundler, your `LOAD_PATH` is changed based on whatever gems are explicitly listed in your `Gemfile`. There's nothing `childprocess` can do about this—you need to configure your `Gemfile` appropriately if you are going to be running your application via `bundle exec` or similar.

Hope that helps!

**Comment by ahorek** [comment]
You're right, but I also don't have gem 'childprocess' in my Gemfile explicitly, other gems depend on it. The same way 'ffi' should be a runtime dependency of 'childprocess'.
It's not a big deal for me and the workaround works.

**Comment by sds** [comment]
Ah, understood. This is an unfortunate case, but there's a good reason we don't include the `ffi` gem by default, which are described in the PR you reference. Most users don't need it, and installing a gem that requires native extensions to be built increases install time substantially. 

Whichever gems are depending on `childprocess` should also be including an explicit dependency on `ffi` if they want to support Windows. Suggest you open an issue on those gems.

**Comment by sds** [comment]
Following up here to say we've removed the magic `ffi` install logic in #160. Recommend you always include `ffi` as a dependency in your `Gemfile` going forward. Thanks!
