### ISSUE TITLE
 Resource unavailable 

### ISSUE THREAD

**Issue by garybunofsky** [enkessler/childprocess#153]
Hi, I’d like start by saying this _might_ be an issue. And if it is, I’m not entirely sure it stems from childprocess. I’m simply asking because I don’t know where to start debugging. 

So I have a rails app running resque and redis with about 5 workers. I'm scheduling jobs about every 5 seconds and the workers are able to keep up with that interval. Anyways, the workers run for about 10-30 minutes and then everything comes to a halt and then I get this error:

2019-06-26T02:17:54.776136+00:00 app[worker_2.1]: /app/vendor/bundle/ruby/2.5.0/gems/childprocess-0.9.0/lib/childprocess/unix/fork_exec_process.rb:20: warning: pthread_create failed for timer: Resource temporarily unavailable, scheduling broken

I googled the error and couldn’t find similar issues, but I did find this repo. I tried upgrading the workers RAM/CPU. I also tried reducing the number of workers and increasing the interval in which jobs fire. Neither helped unfortunately. 

Does anyone know why the resource become unavailable? 

Any insight is much appreciated! Thanks

**Comment by sds** [comment]
Hey @garybunofsky, I'll start by saying it is highly unlikely to be an issue with ChildProcess. With that said, let's follow the trail and see where it takes us.

Regarding the stack trace you see: the error is thrown by `Kernel.fork`, suggesting a low-level issue: https://github.com/enkessler/childprocess/blob/c005912c7e13422bc036ec59eaa9dc1570d78d4d/lib/childprocess/unix/fork_exec_process.rb#L20

Based on your stack trace, you're running Ruby 2.5. Searching for the error message in Ruby's source code we see that this is in response to a unsuccessful call to `pthread_create`: 
https://github.com/ruby/ruby/blob/4e0a512972cdcbfcd5279f1a2a81ba342ed75b6e/thread_pthread.c#L1659-L1661

A search for `"Resource temporarily unavailable" pthread_create` reveals the following thread: https://unix.stackexchange.com/questions/253903/creating-threads-fails-with-resource-temporarily-unavailable-with-4-3-kernel

Now, there's far too much information specific to your system that only you will be able to answer, but hopefully that thread can direct you to areas you can further investigate on your system. Good luck!
