### ISSUE TITLE
Erro ao rodar o comando rspec -fd

### ISSUE THREAD

**Issue by julianacarlas** [enkessler/childprocess#165]
An error occurred while loading spec_helper.
Failure/Error: require 'selenium-webdriver'

ChildProcess::MissingFFIError:
  FFI is a required pre-requisite for Windows or posix_spawn support in the ChildProcess gem. Ensure the `ffi` gem is installed. If you believe this is an error, please file a bug at http://github.com/enkessler/childprocess/issues
# ./spec/spec_helper.rb:3:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- selenium-webdriver
#   ./spec/spec_helper.rb:3:in `<top (required)>'
No examples found.
No examples found.

Finished in 0.00006 seconds (files took 2.26 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00006 seconds (files took 2.26 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

![image](https://user-images.githubusercontent.com/62630423/77492363-2874b480-6e1f-11ea-80e6-868c5785e9d0.png)

**Comment by sds** [comment]
Hey @julianacarlas,

As is documented in the [Requirements](https://github.com/enkessler/childprocess#requirements) section of the documentation:
>Windows users **must** ensure the `ffi` gem (`>= 1.0.11`) is installed in order to use ChildProcess.

Make sure `ffi` is included in your `Gemfile` if running via `bundle exec`, or running `gem install ffi` before attempting to run your command. Hope this helps!
