### ISSUE TITLE
FFI is a required pre-requisite for Windows or posix_spawn support in the ChildProcess gem.

### ISSUE THREAD

**Issue by marcusdesouza27** [enkessler/childprocess#169]
FFI is installed but when I run a bundle exec, i see this error:

FFI is a required pre-requisite for Windows or posix_spawn support in the ChildProcess gem. Ensure the `ffi` gem is installed. If you believe this is an error, please file a bug at http://github.com/enkessler/childprocess/issues (ChildProcess::MissingFFIError)
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/childprocess-3.0.0/lib/childprocess/windows.rb:6:in `rescue in <top (required)>'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/childprocess-3.0.0/lib/childprocess/windows.rb:3:in `<top (required)>'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/childprocess-3.0.0/lib/childprocess.rb:209:in `require'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/childprocess-3.0.0/lib/childprocess.rb:209:in `<top (required)>'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver.rb:20:in `require'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver.rb:20:in `<top (required)>'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium-webdriver.rb:20:in `require'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium-webdriver.rb:20:in `<top (required)>'
D:/keyrus/uniquevision/features/support/env.rb:4:in `require'
D:/keyrus/uniquevision/features/support/env.rb:4:in `<top (required)>'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-3.2.0/lib/cucumber/glue/registry_and_more.rb:107:in `load'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-3.2.0/lib/cucumber/glue/registry_and_more.rb:107:in `load_code_file'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-3.2.0/lib/cucumber/runtime/support_code.rb:144:in `load_file'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-3.2.0/lib/cucumber/runtime/support_code.rb:85:in `block in load_files!'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-3.2.0/lib/cucumber/runtime/support_code.rb:84:in `each'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-3.2.0/lib/cucumber/runtime/support_code.rb:84:in `load_files!'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-3.2.0/lib/cucumber/runtime.rb:272:in `load_step_definitions'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-3.2.0/lib/cucumber/runtime.rb:68:in `run!'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-3.2.0/lib/cucumber/cli/main.rb:34:in `execute!'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-3.2.0/bin/cucumber:9:in `<top (required)>'
D:/Ruby26-x64/bin/cucumber:23:in `load'
D:/Ruby26-x64/bin/cucumber:23:in `<main>'

**Comment by sds** [comment]
Hey @marcusdesouza27, this is by design and is mentioned in the requirements section of the [README](https://github.com/enkessler/childprocess#requirements). We don't include this by default as `ffi` isn't required in the vast majority of installations. You must install it yourself by either manually installing via `gem install ffi`, or if invoking via Bundler adding to your project's `Gemfile` explicitly.
