### ISSUE TITLE
code hanging attempting to @thread.join

### ISSUE THREAD

**Issue by titusfortner** [enkessler/childprocess#174]
This is coming from this issue:
https://github.com/SeleniumHQ/selenium/issues/9104

Reproduction is very straightforward.
I debugged it to this line: https://github.com/enkessler/childprocess/blob/c6260739e86c1cabd9baebd76f2058eea2b1ae16/lib/childprocess/jruby/pump.rb#L14

Not sure why it is getting hung up, what thread join is doing and if it is necessary in all contexts.

**Comment by sds** [comment]
Now that we've switched backends to use Ruby's built-in `Process.spawn`, this might no longer be an issue. With that said, I haven't tested personally.

If you're still seeing this issue and care about it's resolution, feel free to open a new issue. Thanks!
