### ISSUE TITLE
Use with StringIO

### ISSUE THREAD

**Issue by alexeyr-ci1** [enkessler/childprocess#183]
The basic example says
```
# ...or pass an IO
process.io.stdout = Tempfile.new("child-output")
```
This sounds like a `StringIO` should work. But
```
irb(main):001:0> p = ChildProcess.build("ls")
=> #<ChildProcess::Unix::PosixSpawnProcess:0x000055e6766ab500 @args=["ls"], @started=false, @exit_code=nil, @io=nil, @cwd=nil, @detach=false, @dupl...  
irb(main):002:0> p.io.stdout = StringIO.new
Traceback (most recent call last):
        1: from (irb):2
ArgumentError (expected #<StringIO:0x000055e6799b3448> to respond to :to_io)
```

**Comment by sds** [comment]
This may still be an issue, but since #175 made a lot of low-level changes, this _may_ have been resolved.

If you're still seeing this problem, feel free to open a new issue. Thanks!

**Comment by eregon** [comment]
It's not possible to spawn a subprocess and have it write directly to a StringIO:
```
> system 'uname', out: StringIO.new
(irb):6:in `system': wrong exec redirect action (ArgumentError)
```
So this cannot be supported directly.

If you need it you can write to a Tempfile, wait the process, copy from the tempfile to the StringIO or whatever, and close the Tempfile.
