### ISSUE TITLE
posix_spawn is not yet supported on aarch64-linux (aarch64-linux),

### ISSUE THREAD

**Issue by copiousfreetime** [enkessler/childprocess#186]
I'm using Docker Desktop for macOS and this error popped up. In a program that uses childprocss. I'm pretty sure that this i an error. 

I'll work on a PR in the next week to add a new Platform item for `aarch64-linux`.

**Comment by eregon** [comment]
https://github.com/enkessler/childprocess/pull/175 would solve this.

**Comment by sds** [comment]
Resolved by #175. Thanks!
