### ISSUE TITLE
posix_spawn is not yet supported on sparc-solaris (sparc-solaris2.11)

### ISSUE THREAD

**Issue by ryanitguru** [enkessler/childprocess#187]
posix_spawn is not yet supported on sparc-solaris (sparc-solaris2.11), falling back to default implementation. If you believe this is an error, please file a bug at http://github.com/jarib/childprocess/issues

**Comment by sds** [comment]
We've replaced all backends with Ruby's built-in `Process.spawn` for portability. Try upgrading to `childprocess` 5.x, which was just released.
