### ISSUE TITLE
I happen to be having this error after even having all both ruby, gem, and even chocolatey handy

### ISSUE THREAD

**Issue by Carey99** [enkessler/childprocess#189]
`C:/HashiCorp/Vagrant/embedded/gems/gems/childprocess-4.1.0/lib/childprocess/windows.rb:6:in `rescue in <top (required)>': FFI is a required pre-requisite for Windows or posix_spawn support in the ChildProcess gem. Ensure the `ffi` gem is installed. If you believe this is an error, please file a bug at http://github.com/enkessler/childprocess/issues (ChildProcess::MissingFFIError)`

**Comment by xgrid-muhammadniazi** [comment]
I have been stuck with this error as well. Is there anything we are missing? Anyone with any possible direction towards a solution; we would help the assist.

**Comment by sds** [comment]
Try the latest version 5.x, which was just released. We removed the `ffi` requirement.
