### ISSUE TITLE
differences between macos and linux

### ISSUE THREAD

**Issue by jjb** [enkessler/childprocess#195]
i have this code in a test which works well on macos

```ruby
process = ChildProcess.build('mydir/myscript')
r, w = IO.pipe
process.io.stdout = w
process.start
w.close

expect(r.readline.strip).to eq("starting up...")

process.stop

expect(r.readline.strip).to eq('Shutting down...')
expect(process.exit_code).to eq(0)
```

on linux, there are two differences

1. after `process.stop`, the `r.readline` hangs forever. hold that thought, and let's just comment this out for now and run the test again...
2. exit_code is 15, not 0. 15 is the standard code for if a process receives `TERM` and doesn't trap it, something along those lines. I know from when i previously ran this test using `Open3.popen3`, and saw similar differences on mac/linux, that this is likely caused by the command being "wrapped" in `sh -c` on linux, but not on mac.
3. meanwhile, that hanging `r.readline`... while hacking around with a `binding.pry` right before the shutdown output check, i invoked `r.readline` and saw it hang. after a bit i did control-c, and boom, the expected shutdown string suddenly appeared in my shell. i think something about the implementation of how pry implements control-c support (runs every command in a thread?) maybe revealed the behavior difference on linux -- somehow after `process.stop`, the stdout gets reassigned to the outer process? something like that?

grasping at straws here based on what i observed and my limited knowledge.

**Comment by eregon** [comment]
BTW:
https://github.com/enkessler/childprocess/blob/127a3d14b6db54e62961d4e8d93e65617d24f9c5/lib/childprocess/process_spawn_process.rb#L75-L80
So ChildProcess should never use a shell around the subprocess.

**Comment by jjb** [comment]
okay, thanks so much for all for the info. sorry for no reproduction script. i hacked around with it inside a circleCI ssh session and am sure i did everything parallel in both environments. prob won't have time to dig deeper.
