### ISSUE TITLE
StringIO does not respond to to_io

### ISSUE THREAD

**Issue by phene** [enkessler/childprocess#198]
Redux of: https://github.com/enkessler/childprocess/issues/183

```
childprocess-5.0.0/lib/childprocess/unix/io.rb:8:in `check_type': expected #<StringIO:0x0000000109f502d0> to respond to :to_io (ArgumentError)
childprocess-5.0.0/lib/childprocess/abstract_io.rb:16:in `stdout='
```

This expectation restricts the use of a lot of custom IO options and loggers.

StringIO is also does not include the IO module, so the subsequent check would also fail.

**Comment by sds** [comment]
Thanks for opening an issue @phene and @eregon for the additional context. Going to close but if we're missing something let us know!
