### ISSUE TITLE
Cucumber (ChildProcess::LaunchError) on WIndows7 64bit

### ISSUE THREAD

**Issue by ghost** [enkessler/childprocess#53]
When running cucumber features against an android application running on a windows 7 64bit machine I get Unknown error (Windows says "The operation completed successfully.", but it did not.) (ChildProcess::LaunchError).

ruby 1.9.3p125 (2012-02-16) [i386-mingw32]
## bundle update

Using rake (10.1.0)
 Using ffi (1.9.0)
 Using childprocess (0.3.9)
 Using ADB (0.5.6)
 Using brazenhead (0.4.7)
 Using builder (3.2.2)
 Using diff-lcs (1.2.4)
 Using multi_json (1.7.7)
 Using gherkin (2.12.0)
 Using multi_test (0.0.1)
 Using cucumber (1.3.3)
 Using i18n (0.6.4)
 Using faker (1.1.2)
 Using yml_reader (0.2)
 Using data_magic (0.14)
 Using page_navigation (0.9)
 Using gametel (0.7)
 Using require_all (1.2.1)
 Using rspec-core (2.14.1)
 Using rspec-expectations (2.14.0)
 Using rspec-mocks (2.14.1)
 Using rspec (2.14.0)
 Using bundler (1.0.22)

---

[31m  Unknown error (Windows says "The operation completed successfully.", but it did not.) (ChildProcess::LaunchError)[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/childprocess-0.3.9/lib/childprocess/windows/process_builder.rb:87:in `create_process'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/childprocess-0.3.9/lib/childprocess/windows/process_builder.rb:34:in`start'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/childprocess-0.3.9/lib/childprocess/windows/process.rb:63:in `launch_process'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/childprocess-0.3.9/lib/childprocess/abstract_process.rb:72:in`start'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/process.rb:12:in `run'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/manifest_info.rb:32:in`load_manifest'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/manifest_info.rb:28:in `manifest'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/manifest_info.rb:37:in`first_capture'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/manifest_info.rb:7:in `package'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/builder.rb:68:in`the_target'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/builder.rb:58:in `update_test_manifest'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/builder.rb:30:in`block in install_server'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/builder.rb:28:in `chdir'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/builder.rb:28:in`install_server'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/builder.rb:20:in `block in build_for'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/tmpdir.rb:83:in`mktmpdir'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/builder.rb:19:in `build_for'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/server.rb:26:in`build'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/brazenhead-0.4.7/lib/brazenhead/server.rb:15:in `start'[0m
[31m  D:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/gametel-0.7/lib/gametel.rb:41:in`start'[0m
[31m  D:/eBook/cucumber/cukes_and_cheese/android_puppies/features/support/env.rb:18:in `Before'[0m

**Comment by smartfacecommercialtester** [comment]
Hi Jarib,
I got the similar issue, with ADB gem which uses ChildProcess. When I run my cucumber test on local computer everything works. But if I start the test on same machine as Jenkins client I get this error:
The system cannot find the file specified. (2) (ChildProcess::LaunchError)

I added the ADB.rb code. Please help

def execute_adb_with_exactly(timeout, *arguments)
    process = ChildProcess.build('adb', *arguments)
    process.io.stdout, process.io.stderr = std_out_err
    process.start
    kill_if_longer_than(process, timeout)
    @last_stdout = output(process.io.stdout)
    @last_stderr = output(process.io.stderr)
  end

**Comment by smartfacecommercialtester** [comment]
Hi,
I figured the issue. It was related to Jenkins PATH env. variable. I added slave's adb path before building job.
Thanks anyway.
