### ISSUE TITLE
Feature Request: Wrap Existing Process

### ISSUE THREAD

**Issue by Ajedi32** [enkessler/childprocess#57]
I'd like the ability to provide ChildProcess with the PID of some process (potentially started by some external script) and have it wrap the process with that PID.

Example:

``` ruby
process = ChildProcess.wrap(some_pid)
process.alive? #=> true
process.stop
```

**Comment by bogdanRada** [comment]
+1

**Comment by asiazhang** [comment]
+1

**Comment by sds** [comment]
Closing as there doesn't seem to be interest from the community in implementing this, and we have no intention to implement ourselves. A well-tested pull request would be very much welcome!

Closing and locking thread.
