### ISSUE TITLE
ChildProcess::LaunchError: No such file or directory

### ISSUE THREAD

**Issue by moskanz** [enkessler/childprocess#75]
Hi, I have some problems with simple example:

process = ChildProcess.build("ruby", "-e", "sleep")
process.start

ChildProcess::LaunchError: No such file or directory - -e

MacOs 10.9.2, ruby 2.1.0, childprocess 0.5.1

**Comment by jnraine** [comment]
In case someone else hits this issue in the future: a co-worker of mine submitted a patch that has been accepted to Ruby trunk that should remedy the issue with `Kernel#exec`: https://bugs.ruby-lang.org/issues/12355

Hopefully this issue no longer occurs in Ruby 2.3.2!
